name: Terraform Workflow

on:
  push:
    branches:
      - terraform
    # paths:
    #   - '*.tf'

jobs:
  build-infrastructure:
    runs-on: self-hosted

    steps:
      - name: Get sources
        uses: actions/checkout@v3

      - name: Terraform init
        run: terraform init

      - name: List directories
        run: ls -a

      - name: Upload Terraform artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-artifacts
          path: .terraform
          if-no-files-found: error
          include-hidden-files: true

      - name: Terraform apply
        # working-directory: ./terraform
        # uses: hashicorp/terraform-github-actions@v2
        run: terraform apply
      #
      # - name: Run failure
      #   run: terraform apply

      #
      # - name: Delete artifacts (???)
      #   run: terraform apply
