name: Terraform Workflow

on:
  push:
    branches:
      - terraform
    # paths:
    #   - '*.tf'

jobs:
  build-infrastructure:
    runs-on: self-hosted

    steps:
      - name: Get sources
        uses: actions/checkout@v3

      # - name: Terraform init
      #   run: terraform init

      # - name: Upload Terraform artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: terraform-artifacts
      #     path: .terraform
      #     if-no-files-found: error
      #     include-hidden-files: true

      - name: Terraform init - FAIL
        working-directory: ./tf_fail
        run: terraform init

      - name: Terraform apply - FAIL
        working-directory: ./tf_fail
        # uses: hashicorp/terraform-github-actions@v2
        run: terraform apply -auto-approve
      #
      # - name: Run failure
      #   run: terraform apply

      - name: Terraform init - PASS
        if: ${{ failure() }}
        working-directory: ./tf_pass
        run: terraform init

      - name: Terraform apply - PASS
        working-directory: ./tf_pass
        # uses: hashicorp/terraform-github-actions@v2
        run: terraform apply -auto-approve

      #
      # - name: Delete artifacts (???)
      #   run: terraform apply
