name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 
    container:
      image: gh_action_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
