name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 
    # container:
    #   image: gh_action_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build run environment
        run: docker build -t gh_action_test .

      - name: Run container
        run: docker run gh_action_test
